spring:
  datasource :
    url : jdbc:postgresql://165.227.143.73:5432/spm
    username : postgres
    password : pa$$word
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto : update