spring:
  datasource :
#    url : ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spm}
#    username : postgres
#    password : PoSt123!@#
#    driver-class-name: org.postgresql.Driver

    url: jdbc:h2:mem:testesfdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto : update