spring:
  datasource :
    url : jdbc:postgresql://164.92.190.231:5432/spm
    username : postgres
    password : pa$$word
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto : update